services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: studentdb
<<<<<<< HEAD
=======
    ports:
      - "3306:3306"
>>>>>>> e49a2be218bc9ea152bfb0baac163996370cd3f3
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10

  student-app:
    build: .
    container_name: student-app
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
<<<<<<< HEAD
      - "8081:8081"
=======
      - "8081:8081"
>>>>>>> e49a2be218bc9ea152bfb0baac163996370cd3f3
