version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"

  student-app:
    build: .
    container_name: student-app
    depends_on:
      - mysql-db
    ports:
      - "8081:8081"